name: Arduino Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Ejecutar Arduino Lint
        uses: arduino/arduino-lint-action@v1
        with:
          # 'submit' activa las reglas estrictas necesarias para entrar al índice oficial
          library-manager: submit
          # 'true' muestra advertencias adicionales de estilo
          compliance: strict
          
